'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace _1_HelloASP.Web


    Partial Public Class __ASPNETSilverlight

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ScriptManager1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ScriptManager1 As System.Web.UI.ScriptManager

        ''' <summary>
        ''' Silverlight1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Silverlight1 As System.Web.UI.SilverlightControls.Silverlight

        ''' <summary>
        ''' Silverlight2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Silverlight2 As System.Web.UI.SilverlightControls.Silverlight

        ''' <summary>
        ''' Button1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button1 As System.Web.UI.WebControls.Button
    End Class
End Namespace
