'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

namespace _1_HelloASP.Web 

    Partial Public Class __MediaPlayerControl

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ScriptManager1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ScriptManager1 As System.Web.UI.ScriptManager

        ''' <summary>
        ''' MediaPlayer1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MediaPlayer1 As System.Web.UI.SilverlightControls.MediaPlayer

        ''' <summary>
        ''' Basic control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Basic As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' Classic control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Classic As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' Console control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Console As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' Expression control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Expression As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' Futuristic control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Futuristic As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' Professional control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Professional As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' Simple control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Simple As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' DisableGPU control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DisableGPU As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' CacheVisual control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected CacheVisual As System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' HighQuality control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected HighQuality As System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
