Imports System

' ------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:4.0.30319.1
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

'  Original file name:
'  Generation date: 1/30/2011 6:28:31 PM
' Namespace AdoDataServiceClient.SilverlightResourceReference

''' <summary>
''' There are no comments for SilverlightResourceEntities in the schema.
''' </summary>
Partial Public Class SilverlightResourceEntities
    Inherits Data.Services.Client.DataServiceContext
    ''' <summary>
    ''' Initialize a new SilverlightResourceEntities object.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Sub New(serviceRoot As Uri)
        MyBase.New(serviceRoot)
        Me.ResolveName = New Func(Of Type, String)(AddressOf ResolveNameFromType)
        Me.ResolveType = New Func(Of String, Type)(AddressOf ResolveTypeFromName)
        Me.OnContextCreated()
    End Sub '   New

    Partial Private Sub OnContextCreated()

    End Sub '   OnContextCreated
    ''' <summary>
    ''' Since the namespace configured for this service reference
    ''' in Visual Studio is different from the one indicated in the
    ''' server schema, use type-mappers to map between the two.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Protected Function ResolveTypeFromName(typeName As String) As Type

        If (typeName.StartsWith("SilverlightResourceModel", StringComparison.Ordinal)) Then
            Return Me.GetType().Assembly.GetType(String.Concat("AdoDataServiceClient.SilverlightResourceReference", typeName.Substring(24)), False)
        End If

        Return Nothing
    End Function  '   ResolveTypeFromName
    ''' <summary>
    ''' Since the namespace configured for this service reference
    ''' in Visual Studio is different from the one indicated in the
    ''' server schema, use type-mappers to map between the two.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Protected Function ResolveNameFromType(clientType As Type) As String


        If (clientType.Namespace.Equals("AdoDataServiceClient.SilverlightResourceReference", StringComparison.Ordinal)) Then
            Return String.Concat("SilverlightResourceModel.", clientType.Name)
        End If

        Return Nothing
    End Function  '   ResolveNameFromType
    ''' <summary>
    ''' There are no comments for Resource in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public ReadOnly Property Resource() As Data.Services.Client.DataServiceQuery(Of Resource)
        Get

            If ((Me._Resource Is Nothing)) Then
                Me._Resource = MyBase.CreateQuery(Of Resource)("Resource")
            End If

            Return Me._Resource
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _Resource As Data.Services.Client.DataServiceQuery(Of Resource)
    ''' <summary>
    ''' There are no comments for ResourceType in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public ReadOnly Property ResourceType() As Data.Services.Client.DataServiceQuery(Of ResourceType)
        Get

            If ((Me._ResourceType Is Nothing)) Then
                Me._ResourceType = MyBase.CreateQuery(Of ResourceType)("ResourceType")
            End If

            Return Me._ResourceType
        End Get
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _ResourceType As Data.Services.Client.DataServiceQuery(Of ResourceType)
    ''' <summary>
    ''' There are no comments for Resource in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Sub AddToResource(oResource As Resource)

        MyBase.AddObject("Resource", oResource)
    End Sub '   AddToResource
    ''' <summary>
    ''' There are no comments for ResourceType in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Sub AddToResourceType(oResourceType As ResourceType)

        MyBase.AddObject("ResourceType", oResourceType)
    End Sub '   AddToResourceType
End Class   '   SilverlightResourceEntities
''' <summary>
''' There are no comments for SilverlightResourceModel.Resource in the schema.
''' </summary>
''' <KeyProperties>
''' Id
''' </KeyProperties>
<Data.Services.Common.DataServiceKeyAttribute("Id")>
Partial Public Class Resource
    ''' <summary>
    ''' Create a new Resource object.
    ''' </summary>
    ''' <param name="ID">Initial value of Id.</param>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Shared Function CreateResource(ID As Integer) As Resource
        Dim oResource As Resource = New Resource()

        oResource.Id = ID
        Return oResource
    End Function
    ''' <summary>
    ''' There are no comments for Property Id in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property Id() As Integer
        Get

            Return Me._Id
        End Get

        Set(value As Integer)

            Me.OnIdChanging(value)
            Me._Id = value
            Me.OnIdChanged()
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _Id As Integer

    Partial Private Sub OnIdChanging(value As Integer)

    End Sub '   OnIdChanging

    Partial Private Sub OnIdChanged()

    End Sub '   OnIdChanged
    ''' <summary>
    ''' There are no comments for Property Title in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property Title() As String
        Get

            Return Me._Title
        End Get

        Set(value As String)

            Me.OnTitleChanging(value)
            Me._Title = value
            Me.OnTitleChanged()
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _Title As String

    Partial Private Sub OnTitleChanging(value As String)

    End Sub '   OnTitleChanging

    Partial Private Sub OnTitleChanged()

    End Sub '   OnTitleChanged
    ''' <summary>
    ''' There are no comments for Property Author in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property Author() As String
        Get

            Return Me._Author
        End Get

        Set(value As String)

            Me.OnAuthorChanging(value)
            Me._Author = value
            Me.OnAuthorChanged()
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _Author As String

    Partial Private Sub OnAuthorChanging(value As String)

    End Sub '   OnAuthorChanging

    Partial Private Sub OnAuthorChanged()

    End Sub '   OnAuthorChanged
    ''' <summary>
    ''' There are no comments for Property Image in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property Image() As String
        Get

            Return Me._Image
        End Get

        Set(value As String)

            Me.OnImageChanging(value)
            Me._Image = value
            Me.OnImageChanged()
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _Image As String

    Partial Private Sub OnImageChanging(value As String)

    End Sub '   OnImageChanging

    Partial Private Sub OnImageChanged()

    End Sub '   OnImageChanged
    ''' <summary>
    ''' There are no comments for Property URL in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property URL() As String
        Get

            Return Me._URL
        End Get

        Set(value As String)

            Me.OnURLChanging(value)
            Me._URL = value
            Me.OnURLChanged()
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _URL As String

    Partial Private Sub OnURLChanging(value As String)

    End Sub '   OnURLChanging

    Partial Private Sub OnURLChanged()

    End Sub '   OnURLChanged
    ''' <summary>
    ''' There are no comments for ResourceType in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property ResourceType() As ResourceType
        Get

            Return Me._ResourceType
        End Get

        Set(value As ResourceType)

            Me._ResourceType = value
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _ResourceType As ResourceType
End Class   '   Resource
''' <summary>
''' There are no comments for SilverlightResourceModel.ResourceType in the schema.
''' </summary>
''' <KeyProperties>
''' Id
''' </KeyProperties>
<Data.Services.Common.DataServiceKeyAttribute("Id")>
Partial Public Class ResourceType
    ''' <summary>
    ''' Create a new ResourceType object.
    ''' </summary>
    ''' <param name="ID">Initial value of Id.</param>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Shared Function CreateResourceType(ID As Integer) As ResourceType

        Dim oResourceType As ResourceType = New ResourceType()
        oResourceType.Id = ID
        Return oResourceType
    End Function
    ''' <summary>
    ''' There are no comments for Property Id in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property Id() As Integer
        Get

            Return Me._Id
        End Get

        Set(value As Integer)

            Me.OnIdChanging(value)
            Me._Id = value
            Me.OnIdChanged()
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _Id As Integer

    Partial Private Sub OnIdChanging(value As Integer)
    End Sub '   OnIdChanging

    Partial Private Sub OnIdChanged()
    End Sub '   OnIdChanged
    ''' <summary>
    ''' There are no comments for Property Name in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property Name() As String
        Get

            Return Me._Name
        End Get

        Set(value As String)

            Me.OnNameChanging(value)
            Me._Name = value
            Me.OnNameChanged()
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _Name As String

    Partial Private Sub OnNameChanging(value As String)

    End Sub '   OnNameChanging

    Partial Private Sub OnNameChanged()

    End Sub '   OnNameChanged
    ''' <summary>
    ''' There are no comments for Resource in the schema.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Public Property Resource() As Collections.ObjectModel.Collection(Of Resource)
        Get

            Return Me._Resource
        End Get
        Set(value As Collections.ObjectModel.Collection(Of Resource))

            If (value IsNot Nothing) Then
                Me._Resource = value
            End If
        End Set
    End Property

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>
    Private _Resource As Collections.ObjectModel.Collection(Of Resource) = New Collections.ObjectModel.Collection(Of Resource)()
End Class   '   ResourceType
' End Namespace   '   AdoDataServiceClient.SilverlightResourceReference
' ..\Project_07\ASPAJAX\4-AdoDataService\AdoDataServiceClient\Service References\SilverlightResourceReference\Reference.cs
