
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("90b8bc5a-baf6-49fc-8947-244b4e9d07cc")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("SilverlightResourceModel", "FK_Resource_ResourceType", "ResourceType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(ResourceType), "Resource", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Resource))>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class SilverlightResourceEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new SilverlightResourceEntities object using the connection string found in the 'SilverlightResourceEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=SilverlightResourceEntities", "SilverlightResourceEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new SilverlightResourceEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "SilverlightResourceEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new SilverlightResourceEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "SilverlightResourceEntities")
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Resource() As ObjectSet(Of Resource)
        Get
            If (_Resource Is Nothing) Then
                _Resource = MyBase.CreateObjectSet(Of Resource)("Resource")
            End If
            Return _Resource
        End Get
    End Property

    Private _Resource As ObjectSet(Of Resource)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ResourceType() As ObjectSet(Of ResourceType)
        Get
            If (_ResourceType Is Nothing) Then
                _ResourceType = MyBase.CreateObjectSet(Of ResourceType)("ResourceType")
            End If
            Return _ResourceType
        End Get
    End Property

    Private _ResourceType As ObjectSet(Of ResourceType)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Resource EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToResource(ByVal resource As Resource)
        MyBase.AddObject("Resource", resource)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ResourceType EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToResourceType(ByVal resourceType As ResourceType)
        MyBase.AddObject("ResourceType", resourceType)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SilverlightResourceModel", Name:="Resource")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Resource
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Resource object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateResource(id As Global.System.Int32) As Resource
        Dim resource as Resource = New Resource
        resource.Id = id
        Return resource
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Title() As Global.System.String
        Get
            Return _Title
        End Get
        Set
            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property

    Private _Title As Global.System.String
    Private Partial Sub OnTitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Author() As Global.System.String
        Get
            Return _Author
        End Get
        Set
            OnAuthorChanging(value)
            ReportPropertyChanging("Author")
            _Author = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Author")
            OnAuthorChanged()
        End Set
    End Property

    Private _Author As Global.System.String
    Private Partial Sub OnAuthorChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAuthorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Image() As Global.System.String
        Get
            Return _Image
        End Get
        Set
            OnImageChanging(value)
            ReportPropertyChanging("Image")
            _Image = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Image")
            OnImageChanged()
        End Set
    End Property

    Private _Image As Global.System.String
    Private Partial Sub OnImageChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnImageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property URL() As Global.System.String
        Get
            Return _URL
        End Get
        Set
            OnURLChanging(value)
            ReportPropertyChanging("URL")
            _URL = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("URL")
            OnURLChanged()
        End Set
    End Property

    Private _URL As Global.System.String
    Private Partial Sub OnURLChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnURLChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SilverlightResourceModel", "FK_Resource_ResourceType", "ResourceType")>
    Public Property ResourceType() As ResourceType
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ResourceType)("SilverlightResourceModel.FK_Resource_ResourceType", "ResourceType").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ResourceType)("SilverlightResourceModel.FK_Resource_ResourceType", "ResourceType").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ResourceTypeReference() As EntityReference(Of ResourceType)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ResourceType)("SilverlightResourceModel.FK_Resource_ResourceType", "ResourceType")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ResourceType)("SilverlightResourceModel.FK_Resource_ResourceType", "ResourceType", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SilverlightResourceModel", Name:="ResourceType")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ResourceType
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ResourceType object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateResourceType(id As Global.System.Int32) As ResourceType
        Dim resourceType as ResourceType = New ResourceType
        resourceType.Id = id
        Return resourceType
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SilverlightResourceModel", "FK_Resource_ResourceType", "Resource")>
     Public Property Resource() As EntityCollection(Of Resource)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Resource)("SilverlightResourceModel.FK_Resource_ResourceType", "Resource")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Resource)("SilverlightResourceModel.FK_Resource_ResourceType", "Resource", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

