//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressionMediaPlayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaPlayer.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an instance of TimeCode..
        /// </summary>
        public static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonOfflineProgressCancel {
            get {
                return ResourceManager.GetString("buttonOfflineProgressCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string buttonOfflineProgressFinish {
            get {
                return ResourceManager.GetString("buttonOfflineProgressFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} captions.
        /// </summary>
        public static string captionsCaptions {
            get {
                return ResourceManager.GetString("captionsCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} description.
        /// </summary>
        public static string captionsDescriptive {
            get {
                return ResourceManager.GetString("captionsDescriptive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading captions {0}.
        /// </summary>
        public static string captionsDownloading {
            get {
                return ResourceManager.GetString("captionsDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} subtitles.
        /// </summary>
        public static string captionsSubtitles {
            get {
                return ResourceManager.GetString("captionsSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open media file {0}.
        /// </summary>
        public static string errorInvalidMedia {
            get {
                return ResourceManager.GetString("errorInvalidMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Playlist.
        /// </summary>
        public static string errorInvalidPlaylist {
            get {
                return ResourceManager.GetString("errorInvalidPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Playlist: Unexpected node: {0} in {1}.
        /// </summary>
        public static string errorInvalidPlaylistNode {
            get {
                return ResourceManager.GetString("errorInvalidPlaylistNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Requires output to be hosted on a web server running IIS 7.0 with the Smooth Streaming handler installed and a Silverlight template that supports Smooth Streaming..
        /// </summary>
        public static string errorNonSmoothStreamingServer {
            get {
                return ResourceManager.GetString("errorNonSmoothStreamingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offlining interrupted by network loss.
        /// </summary>
        public static string errorOfflineInterrupted {
            get {
                return ResourceManager.GetString("errorOfflineInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected value in range {0} to {1} found {2}.
        /// </summary>
        public static string errorValueOutOfRange {
            get {
                return ResourceManager.GetString("errorValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string readerChapterItem {
            get {
                return ResourceManager.GetString("readerChapterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chapters toggle.
        /// </summary>
        public static string readerChapters {
            get {
                return ResourceManager.GetString("readerChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed captions toggle.
        /// </summary>
        public static string readerClosedCaptions {
            get {
                return ResourceManager.GetString("readerClosedCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step backwards one frame.
        /// </summary>
        public static string readerFrameStepBackwards {
            get {
                return ResourceManager.GetString("readerFrameStepBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step forwards one frame.
        /// </summary>
        public static string readerFrameStepForwards {
            get {
                return ResourceManager.GetString("readerFrameStepForwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen toggle.
        /// </summary>
        public static string readerFullScreen {
            get {
                return ResourceManager.GetString("readerFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one hour.
        /// </summary>
        public static string readerHour {
            get {
                return ResourceManager.GetString("readerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string readerHours {
            get {
                return ResourceManager.GetString("readerHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute.
        /// </summary>
        public static string readerMinute {
            get {
                return ResourceManager.GetString("readerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string readerMinutes {
            get {
                return ResourceManager.GetString("readerMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Toggle.
        /// </summary>
        public static string readerMute {
            get {
                return ResourceManager.GetString("readerMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to next marker.
        /// </summary>
        public static string readerNextMarker {
            get {
                return ResourceManager.GetString("readerNextMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make player available offline.
        /// </summary>
        public static string readerOffline {
            get {
                return ResourceManager.GetString("readerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the cancel button to stop offline installation.
        /// </summary>
        public static string readerOfflineProgressCancel {
            get {
                return ResourceManager.GetString("readerOfflineProgressCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the finish button to compete offline installation.
        /// </summary>
        public static string readerOfflineProgressFinish {
            get {
                return ResourceManager.GetString("readerOfflineProgressFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show playlist toggle.
        /// </summary>
        public static string readerPlaylist {
            get {
                return ResourceManager.GetString("readerPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist item {0}. {1}..
        /// </summary>
        public static string readerPlaylistItem {
            get {
                return ResourceManager.GetString("readerPlaylistItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play pause toggle.
        /// </summary>
        public static string readerPlayPause {
            get {
                return ResourceManager.GetString("readerPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show graphs.
        /// </summary>
        public static string readerPlugIn {
            get {
                return ResourceManager.GetString("readerPlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player in seperate window.
        /// </summary>
        public static string readerPopout {
            get {
                return ResourceManager.GetString("readerPopout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to previous marker.
        /// </summary>
        public static string readerPreviousMarker {
            get {
                return ResourceManager.GetString("readerPreviousMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second.
        /// </summary>
        public static string readerSecond {
            get {
                return ResourceManager.GetString("readerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string readerSeconds {
            get {
                return ResourceManager.GetString("readerSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek to time.
        /// </summary>
        public static string readerSeekSlider {
            get {
                return ResourceManager.GetString("readerSeekSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string readerStop {
            get {
                return ResourceManager.GetString("readerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease volume.
        /// </summary>
        public static string readerVolumeDown {
            get {
                return ResourceManager.GetString("readerVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set volume.
        /// </summary>
        public static string readerVolumeSlider {
            get {
                return ResourceManager.GetString("readerVolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume.
        /// </summary>
        public static string readerVolumeUp {
            get {
                return ResourceManager.GetString("readerVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 23.98 IVTC..
        /// </summary>
        public static string Smpte12M_2398_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_2398_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 24fps Film Sync..
        /// </summary>
        public static string Smpte12M_24_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_24_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 25fps PAL..
        /// </summary>
        public static string Smpte12M_25_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_25_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 29.97 DropFrame..
        /// </summary>
        public static string Smpte12M_2997_Drop_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_2997_Drop_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMTPE 29.97 NonDrop..
        /// </summary>
        public static string Smpte12M_2997_NonDrop_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_2997_NonDrop_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 30fps..
        /// </summary>
        public static string Smpte12M_30_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_30_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timecode provided is not in the correct format..
        /// </summary>
        public static string Smpte12MBadFormat {
            get {
                return ResourceManager.GetString("Smpte12MBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timecode provided is out of the expected range..
        /// </summary>
        public static string Smpte12MOutOfRange {
            get {
                return ResourceManager.GetString("Smpte12MOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting timecode is out of the expected range of MaxValue..
        /// </summary>
        public static string Smpte12MOverflowException {
            get {
                return ResourceManager.GetString("Smpte12MOverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Finish to complete offline installation.
        /// </summary>
        public static string textOfflineFinishPrompt {
            get {
                return ResourceManager.GetString("textOfflineFinishPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading content for offline playback.
        /// </summary>
        public static string textOfflineProgressPrompt {
            get {
                return ResourceManager.GetString("textOfflineProgressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string textOfflineProgressXOFYFormat {
            get {
                return ResourceManager.GetString("textOfflineProgressXOFYFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle chapters list (C).
        /// </summary>
        public static string tipChapters {
            get {
                return ResourceManager.GetString("tipChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide closed captions (L).
        /// </summary>
        public static string tipClosedCaptions {
            get {
                return ResourceManager.GetString("tipClosedCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step backwards one frame (I).
        /// </summary>
        public static string tipFrameStepBackwards {
            get {
                return ResourceManager.GetString("tipFrameStepBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step forwards one frame (O).
        /// </summary>
        public static string tipFrameStepForwards {
            get {
                return ResourceManager.GetString("tipFrameStepForwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle fullscreen playback (F).
        /// </summary>
        public static string tipFullScreen {
            get {
                return ResourceManager.GetString("tipFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute (M).
        /// </summary>
        public static string tipMute {
            get {
                return ResourceManager.GetString("tipMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Marker (N).
        /// </summary>
        public static string tipNextMarker {
            get {
                return ResourceManager.GetString("tipNextMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make player available offline (D).
        /// </summary>
        public static string tipOffline {
            get {
                return ResourceManager.GetString("tipOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the cancel button to compete offline installation.
        /// </summary>
        public static string tipOfflineProgressCancel {
            get {
                return ResourceManager.GetString("tipOfflineProgressCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Finish to complete offline installation.
        /// </summary>
        public static string tipOfflineProgressFinish {
            get {
                return ResourceManager.GetString("tipOfflineProgressFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle playlist (V).
        /// </summary>
        public static string tipPlaylist {
            get {
                return ResourceManager.GetString("tipPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause (P).
        /// </summary>
        public static string tipPlayPause {
            get {
                return ResourceManager.GetString("tipPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Graphs (G).
        /// </summary>
        public static string tipPlugIn {
            get {
                return ResourceManager.GetString("tipPlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player in seperate window (X).
        /// </summary>
        public static string tipPopout {
            get {
                return ResourceManager.GetString("tipPopout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Marker (B).
        /// </summary>
        public static string tipPreviousMarker {
            get {
                return ResourceManager.GetString("tipPreviousMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek to time.
        /// </summary>
        public static string tipSeekSlider {
            get {
                return ResourceManager.GetString("tipSeekSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop (S).
        /// </summary>
        public static string tipStop {
            get {
                return ResourceManager.GetString("tipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Volume (J).
        /// </summary>
        public static string tipVolumeDown {
            get {
                return ResourceManager.GetString("tipVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Slider.
        /// </summary>
        public static string tipVolumeSlider {
            get {
                return ResourceManager.GetString("tipVolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Volume (K).
        /// </summary>
        public static string tipVolumeUp {
            get {
                return ResourceManager.GetString("tipVolumeUp", resourceCulture);
            }
        }
    }
}
