'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Namespace SilverlightResourceASMXService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResourceInfo", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ResourceInfo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private TitleField As String
        
        Private AuthorField As String
        
        Private ImageField As String
        
        Private URLField As String
        
        Private TypeField As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Author() As String
            Get
                Return Me.AuthorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuthorField, value) <> true) Then
                    Me.AuthorField = value
                    Me.RaisePropertyChanged("Author")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Image() As String
            Get
                Return Me.ImageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageField, value) <> true) Then
                    Me.ImageField = value
                    Me.RaisePropertyChanged("Image")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property URL() As String
            Get
                Return Me.URLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.URLField, value) <> true) Then
                    Me.URLField = value
                    Me.RaisePropertyChanged("URL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Type() As String
            Get
                Return Me.TypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeField, value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SilverlightResourceASMXService.SilverlightResourceSoap")>  _
    Public Interface SilverlightResourceSoap
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/GetResource", ReplyAction:="*")>  _
        Function BeginGetResource(ByVal request As SilverlightResourceASMXService.GetResourceRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetResource(ByVal result As System.IAsyncResult) As SilverlightResourceASMXService.GetResourceResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetResourceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetResource", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SilverlightResourceASMXService.GetResourceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SilverlightResourceASMXService.GetResourceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetResourceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetResourceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetResourceResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SilverlightResourceASMXService.GetResourceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SilverlightResourceASMXService.GetResourceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetResourceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetResourceResult As SilverlightResourceASMXService.ResourceInfo
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetResourceResult As SilverlightResourceASMXService.ResourceInfo)
            MyBase.New
            Me.GetResourceResult = GetResourceResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SilverlightResourceSoapChannel
        Inherits SilverlightResourceASMXService.SilverlightResourceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetResourceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As SilverlightResourceASMXService.ResourceInfo
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SilverlightResourceASMXService.ResourceInfo)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SilverlightResourceSoapClient
        Inherits System.ServiceModel.ClientBase(Of SilverlightResourceASMXService.SilverlightResourceSoap)
        Implements SilverlightResourceASMXService.SilverlightResourceSoap
        
        Private onBeginGetResourceDelegate As BeginOperationDelegate
        
        Private onEndGetResourceDelegate As EndOperationDelegate
        
        Private onGetResourceCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event GetResourceCompleted As System.EventHandler(Of GetResourceCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SilverlightResourceASMXService_SilverlightResourceSoap_BeginGetResource(ByVal request As SilverlightResourceASMXService.GetResourceRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SilverlightResourceASMXService.SilverlightResourceSoap.BeginGetResource
            Return MyBase.Channel.BeginGetResource(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginGetResource(ByVal id As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As SilverlightResourceASMXService.GetResourceRequest = New SilverlightResourceASMXService.GetResourceRequest()
            inValue.Body = New SilverlightResourceASMXService.GetResourceRequestBody()
            inValue.Body.id = id
            Return CType(Me,SilverlightResourceASMXService.SilverlightResourceSoap).BeginGetResource(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SilverlightResourceASMXService_SilverlightResourceSoap_EndGetResource(ByVal result As System.IAsyncResult) As SilverlightResourceASMXService.GetResourceResponse Implements SilverlightResourceASMXService.SilverlightResourceSoap.EndGetResource
            Return MyBase.Channel.EndGetResource(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndGetResource(ByVal result As System.IAsyncResult) As SilverlightResourceASMXService.ResourceInfo
            Dim retVal As SilverlightResourceASMXService.GetResourceResponse = CType(Me,SilverlightResourceASMXService.SilverlightResourceSoap).EndGetResource(result)
            Return retVal.Body.GetResourceResult
        End Function
        
        Private Function OnBeginGetResource(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim id As Integer = CType(inValues(0),Integer)
            Return Me.BeginGetResource(id, callback, asyncState)
        End Function
        
        Private Function OnEndGetResource(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As SilverlightResourceASMXService.ResourceInfo = Me.EndGetResource(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetResourceCompleted(ByVal state As Object)
            If (Not (Me.GetResourceCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetResourceCompleted(Me, New GetResourceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetResourceAsync(ByVal id As Integer)
            Me.GetResourceAsync(id, Nothing)
        End Sub
        
        Public Overloads Sub GetResourceAsync(ByVal id As Integer, ByVal userState As Object)
            If (Me.onBeginGetResourceDelegate Is Nothing) Then
                Me.onBeginGetResourceDelegate = AddressOf Me.OnBeginGetResource
            End If
            If (Me.onEndGetResourceDelegate Is Nothing) Then
                Me.onEndGetResourceDelegate = AddressOf Me.OnEndGetResource
            End If
            If (Me.onGetResourceCompletedDelegate Is Nothing) Then
                Me.onGetResourceCompletedDelegate = AddressOf Me.OnGetResourceCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetResourceDelegate, New Object() {id}, Me.onEndGetResourceDelegate, Me.onGetResourceCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As SilverlightResourceASMXService.SilverlightResourceSoap
            Return New SilverlightResourceSoapClientChannel(Me)
        End Function
        
        Private Class SilverlightResourceSoapClientChannel
            Inherits ChannelBase(Of SilverlightResourceASMXService.SilverlightResourceSoap)
            Implements SilverlightResourceASMXService.SilverlightResourceSoap
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of SilverlightResourceASMXService.SilverlightResourceSoap))
                MyBase.New(client)
            End Sub
            
            Public Function BeginGetResource(ByVal request As SilverlightResourceASMXService.GetResourceRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SilverlightResourceASMXService.SilverlightResourceSoap.BeginGetResource
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetResource", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetResource(ByVal result As System.IAsyncResult) As SilverlightResourceASMXService.GetResourceResponse Implements SilverlightResourceASMXService.SilverlightResourceSoap.EndGetResource
                Dim _args((0) - 1) As Object
                Dim _result As SilverlightResourceASMXService.GetResourceResponse = CType(MyBase.EndInvoke("GetResource", _args, result),SilverlightResourceASMXService.GetResourceResponse)
                Return _result
            End Function
        End Class
    End Class
End Namespace
