' ------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:4.0.30319.261
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

'  This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Imports System.Runtime.Serialization
Imports System.ServiceModel
Imports System.ComponentModel

' Namespace ASMXClient.SilverlightResourceASMXService

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")>
<System.Runtime.Serialization.DataContractAttribute(Name:="ResourceInfo", Namespace:="http://tempuri.org/")>
Partial Public Class ResourceInfo
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged

    Private TitleField As String
    Private AuthorField As String
    Private ImageField As String
    Private URLField As String
    Private TypeField As String

    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False)>
    Public Property Title() As String
        Get
            Return Me.TitleField
        End Get
        Set(value As String)

            If ((Object.ReferenceEquals(Me.TitleField, value) = False)) Then
                Me.TitleField = value
                Me.RaisePropertyChanged("Title")
            End If
        End Set
    End Property

    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)>
    Public Property Author() As String
        Get
            Return Me.AuthorField
        End Get

        Set(value As String)
            If ((Object.ReferenceEquals(Me.AuthorField, value) = False)) Then
                Me.AuthorField = value
                Me.RaisePropertyChanged("Author")
            End If
        End Set
    End Property

    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=2)>
    Public Property Image() As String
        Get
            Return Me.ImageField
        End Get

        Set(value As String)
            If ((Object.ReferenceEquals(Me.ImageField, value) = False)) Then
                Me.ImageField = value
                Me.RaisePropertyChanged("Image")
            End If
        End Set
    End Property

    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=3)>
    Public Property URL() As String
        Get
            Return Me.URLField
        End Get

        Set(value As String)
            If ((Object.ReferenceEquals(Me.URLField, value) = False)) Then
                Me.URLField = value
                Me.RaisePropertyChanged("URL")
            End If
        End Set
    End Property

    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=4)>
    Public Property Type() As String
        Get
            Return Me.TypeField
        End Get

        Set(value As String)
            If ((Object.ReferenceEquals(Me.TypeField, value) = False)) Then
                Me.TypeField = value
                Me.RaisePropertyChanged("Type")
            End If
        End Set
    End Property

    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged

    Private Sub RaisePropertyChanged(propertyName As String)

        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub
    'Protected Sub RaisePropertyChanged(propertyName As String)

    '    Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChanged

    '    '     If ((propertyChanged IsNot Nothing)) Then
    '    RaiseEvent PropertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
    '    '     End If
    'End Sub '   RaisePropertyChanged
End Class   '   ResourceInfo

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
<System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SilverlightResourceASMXService.SilverlightResourceSoap")>
Public Interface SilverlightResourceSoap

    <System.ServiceModel.OperationContractAttribute(AsyncPattern:=True, Action:="http://tempuri.org/GetResource", ReplyAction:="*")> _
    Function BeginGetResource(request As GetResourceRequest, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult
    Function EndGetResource(result As System.IAsyncResult) As GetResourceResponse
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
<System.ServiceModel.MessageContractAttribute(IsWrapped:=False)>
Partial Public Class GetResourceRequest

    <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetResource", Namespace:="http://tempuri.org/", Order:=0)>
    Public Body As GetResourceRequestBody

    Public Sub New()

    End Sub '   New

    Public Sub New(Body As GetResourceRequestBody)

        Me.Body = Body
    End Sub '   New
End Class   '   GetResourceRequest

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
<System.Runtime.Serialization.DataContractAttribute(Namespace:="http://tempuri.org/")>
Partial Public Class GetResourceRequestBody

    <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>
    Public id As Integer

    Public Sub New()

    End Sub '   New

    Public Sub New(id As Integer)

        Me.id = id
    End Sub '   New
End Class   '   GetResourceRequestBody

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
<System.ServiceModel.MessageContractAttribute(IsWrapped:=False)>
Partial Public Class GetResourceResponse

    <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetResourceResponse", Namespace:="http://tempuri.org/", Order:=0)>
    Public Body As GetResourceResponseBody

    Public Sub New()

    End Sub '   New

    Public Sub New(Body As GetResourceResponseBody)

        Me.Body = Body
    End Sub '   New
End Class   '   GetResourceResponse

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
<System.Runtime.Serialization.DataContractAttribute(Namespace:="http://tempuri.org/")>
Partial Public Class GetResourceResponseBody

    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)>
    Public GetResourceResult As ResourceInfo

    Public Sub New()

    End Sub '   New

    Public Sub New(GetResourceResult As ResourceInfo)

        Me.GetResourceResult = GetResourceResult
    End Sub '   New
End Class   '   GetResourceResponseBody

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
Public Interface SilverlightResourceSoapChannel
    Inherits SilverlightResourceSoap
    Inherits System.ServiceModel.IClientChannel

End Interface

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
Partial Public Class GetResourceCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs

    Private results As Object()

    Public Sub New(results As Object(), exception As System.Exception, cancelled As Boolean, userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub '   New

    Public ReadOnly Property Result() As ResourceInfo
        Get
            MyBase.RaiseExceptionIfNecessary()
            Return CType(Me.results(0), ResourceInfo)
        End Get
    End Property
End Class   '   GetResourceCompletedEventArgs

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
Partial Public Class SilverlightResourceSoapClient
    Inherits System.ServiceModel.ClientBase(Of SilverlightResourceSoap)
    Implements SilverlightResourceSoap

    Private onBeginGetResourceDelegate As BeginOperationDelegate
    Private onEndGetResourceDelegate As EndOperationDelegate
    Private onGetResourceCompletedDelegate As System.Threading.SendOrPostCallback
    Private onBeginOpenDelegate As BeginOperationDelegate
    Private onEndOpenDelegate As EndOperationDelegate
    Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
    Private onBeginCloseDelegate As BeginOperationDelegate
    Private onEndCloseDelegate As EndOperationDelegate
    Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback

    Public Sub New()

    End Sub '   New

    Public Sub New(endpointConfigurationName As String)

        MyBase.New(endpointConfigurationName)
    End Sub '   New

    Public Sub New(endpointConfigurationName As String, remoteAddress As String)

        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub '   New

    Public Sub New(endpointConfigurationName As String, remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub '   New

    Public Sub New(binding As System.ServiceModel.Channels.Binding, remoteAddress As System.ServiceModel.EndpointAddress)

        MyBase.New(binding, remoteAddress)
    End Sub '   New

    Public Property CookieContainer() As System.Net.CookieContainer
        Get
            Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)()

            If ((httpCookieContainerManager IsNot Nothing)) Then
                Return httpCookieContainerManager.CookieContainer
            Else
                Return Nothing
            End If
        End Get

        Set(value As System.Net.CookieContainer)
            Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)()

            If ((httpCookieContainerManager IsNot Nothing)) Then
                httpCookieContainerManager.CookieContainer = value
            Else
                Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.")
            End If
        End Set
    End Property

    Public Event GetResourceCompleted As System.EventHandler(Of GetResourceCompletedEventArgs)
    Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
    Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function BeginGetResource(request As GetResourceRequest, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult Implements SilverlightResourceSoap.BeginGetResource

        Return MyBase.Channel.BeginGetResource(request, callback, asyncState)
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
    Private Function BeginGetResource(id As Integer, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult

        Dim inValue As GetResourceRequest = New GetResourceRequest()

        inValue.Body = New GetResourceRequestBody()
        inValue.Body.id = id
        Return (CType(Me, SilverlightResourceSoap)).BeginGetResource(inValue, callback, asyncState)
    End Function  '   BeginGetResource

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
    Function EndGetResource(result As System.IAsyncResult) As GetResourceResponse Implements SilverlightResourceSoap.EndGetResource

        Return MyBase.Channel.EndGetResource(result)
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
    Private Function EndGetResourceP(result As System.IAsyncResult) As ResourceInfo

        Dim retVal As GetResourceResponse = (CType(Me, SilverlightResourceSoap)).EndGetResource(result)

        Return retVal.Body.GetResourceResult
    End Function

    Private Function OnBeginGetResource(inValues As Object(), callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult

        Dim id As Integer = CType(inValues(0), Integer)

        Return Me.BeginGetResource(id, callback, asyncState)
    End Function  '   OnBeginGetResource

    Private Function OnEndGetResource(result As System.IAsyncResult) As Object()

        Dim retVal As ResourceInfo = Me.EndGetResourceP(result)

        Return New Object() {retVal}
    End Function

    Private Sub OnGetResourceCompleted(state As Object)

            Dim e As InvokeAsyncCompletedEventArgs = CType(state, InvokeAsyncCompletedEventArgs)

        RaiseEvent GetResourceCompleted(Me, New GetResourceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
    End Sub '   OnGetResourceCompleted

    Public Sub GetResourceAsync(id As Integer)

        Me.GetResourceAsync(id, Nothing)
    End Sub '   GetResourceAsync

    Public Sub GetResourceAsync(id As Integer, userState As Object)

        If ((Me.onBeginGetResourceDelegate = Nothing)) Then
            Me.onBeginGetResourceDelegate = New BeginOperationDelegate(AddressOf OnBeginGetResource)
        End If

        If ((Me.onEndGetResourceDelegate = Nothing)) Then
            Me.onEndGetResourceDelegate = New EndOperationDelegate(AddressOf OnEndGetResource)
        End If

        If ((Me.onGetResourceCompletedDelegate = Nothing)) Then
            Me.onGetResourceCompletedDelegate = New System.Threading.SendOrPostCallback(AddressOf OnGetResourceCompleted)
        End If

        MyBase.InvokeAsync(Me.onBeginGetResourceDelegate, New Object() {id}, Me.onEndGetResourceDelegate, Me.onGetResourceCompletedDelegate, userState)
    End Sub '   GetResourceAsync

    Private Function OnBeginOpen(inValues As Object(), callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult

        Return (CType(Me, System.ServiceModel.ICommunicationObject)).BeginOpen(callback, asyncState)
    End Function  '   OnBeginOpen

    Private Function OnEndOpen(result As System.IAsyncResult) As Object()

        CType(Me, System.ServiceModel.ICommunicationObject).EndOpen(result)
        Return Nothing
    End Function

    Private Sub OnOpenCompleted(state As Object)

        Dim e As InvokeAsyncCompletedEventArgs = CType(state, InvokeAsyncCompletedEventArgs)
        RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
    End Sub '   OnOpenCompleted

    Public Sub OpenAsync()

        Me.OpenAsync(Nothing)
    End Sub '   OpenAsync

    Public Sub OpenAsync(userState As Object)

        If ((Me.onBeginOpenDelegate = Nothing)) Then
            Me.onBeginOpenDelegate = New BeginOperationDelegate(AddressOf OnBeginOpen)
        End If

        If ((Me.onEndOpenDelegate = Nothing)) Then
            Me.onEndOpenDelegate = New EndOperationDelegate(AddressOf OnEndOpen)
        End If

        If ((Me.onOpenCompletedDelegate = Nothing)) Then
            Me.onOpenCompletedDelegate = New System.Threading.SendOrPostCallback(AddressOf OnOpenCompleted)
        End If

        MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
    End Sub '   OpenAsync

    Private Function OnBeginClose(inValues As Object(), callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult

        Return (CType(Me, System.ServiceModel.ICommunicationObject)).BeginClose(callback, asyncState)
    End Function  '   OnBeginClose

    Private Function OnEndClose(result As System.IAsyncResult) As Object()

        CType(Me, System.ServiceModel.ICommunicationObject).EndClose(result)
        Return Nothing
    End Function

    Private Sub OnCloseCompleted(state As Object)

        Dim e As InvokeAsyncCompletedEventArgs = CType(state, InvokeAsyncCompletedEventArgs)
        RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
    End Sub '   OnCloseCompleted

    Public Sub CloseAsync()

        Me.CloseAsync(Nothing)
    End Sub '   CloseAsync

    Public Sub CloseAsync(userState As Object)

        If ((Me.onBeginCloseDelegate = Nothing)) Then
            Me.onBeginCloseDelegate = New BeginOperationDelegate(AddressOf OnBeginClose)
        End If

        If ((Me.onEndCloseDelegate = Nothing)) Then
            Me.onEndCloseDelegate = New EndOperationDelegate(AddressOf OnEndClose)
        End If

        If ((Me.onCloseCompletedDelegate = Nothing)) Then
            Me.onCloseCompletedDelegate = New System.Threading.SendOrPostCallback(AddressOf OnCloseCompleted)
        End If

        MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
    End Sub '   CloseAsync

    Protected Overrides Function CreateChannel() As SilverlightResourceSoap

        Return New SilverlightResourceSoapClientChannel(Me)
    End Function

    Private Class SilverlightResourceSoapClientChannel
        Inherits ChannelBase(Of SilverlightResourceSoap)
        Implements SilverlightResourceSoap

        Public Sub New(client As System.ServiceModel.ClientBase(Of SilverlightResourceSoap))

            MyBase.New(client)
        End Sub '   New

        Public Function BeginGetResource(request As GetResourceRequest, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult Implements SilverlightResourceSoap.BeginGetResource

            Dim _args() As Object
            ReDim _args(0 To 0)
            _args(0) = request

            Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetResource", _args, callback, asyncState)

            Return _result
        End Function  '   BeginGetResource

        Public Function EndGetResource(result As System.IAsyncResult) As GetResourceResponse Implements SilverlightResourceSoap.EndGetResource

            Dim _args As Object()
            ReDim _args(0 To -1)

            Dim _result As GetResourceResponse = CType(MyBase.EndInvoke("GetResource", _args, result), GetResourceResponse)

            Return _result
        End Function
    End Class   '   SilverlightResourceSoapClientChannel
End Class   '   SilverlightResourceSoapClient
' End Namespace
' ..\Project_08\WebServices\2-ASPNETWebService\ASMXClient\Service References\SilverlightResourceASMXService\Reference.cs
