'--------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:2.0.50727.42
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
'------------------------------------------------------------------------------

' Namespace WCFClient.Web

Partial Public Class _Default

    ''' <summary>
    ''' form1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected form1 As System.Web.UI.HtmlControls.HtmlForm
End Class   '   _Default
' End Namespace
' ..\Project_08\WebServices\3-WCFService\WCFClient.Web\Default.aspx.designer.cs
