' ------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:4.0.30128.1
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

' Namespace ExpressionMediaPlayer

Imports    using System

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    '  This class was auto-generated by the StronglyTypedResourceBuilder
    '  class via a tool like ResGen or Visual Studio.
    '  To add or remove a member, edit your .ResX file then rerun ResGen
    '  with the /str option, or rebuild your VS project.
    <CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Diagnostics.DebuggerNonUserCodeAttribute()>
    <Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Public Class Resources

        Private ReadOnly Property Resources.ResourceManager() As

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
        Public ReadOnly Property Resources.ResourceManager() As
            Get

                if (object.ReferenceEquals(resourceMan, Nothing)) {

                If (object.ReferenceEquals(resourceMan, Nothing)) Then
                    Resources.ResourceManager temp = New Resources.ResourceManager("MediaPlayer.Resources.Resources", GetType(Resources).Assembly)
                End If
                    resourceMan = temp
                }
                return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
        Public Property Globalization.CultureInfo() As
            Get

                return resourceCulture
            End Get

            Set

                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Expected an instance of TimeCode..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("ArgumentException", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cancel.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("buttonOfflineProgressCancel", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Finish.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("buttonOfflineProgressFinish", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} captions.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("captionsCaptions", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} description.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("captionsDescriptive", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Downloading captions {0}.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("captionsDownloading", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} subtitles.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("captionsSubtitles", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Could not open media file {0}.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("errorInvalidMedia", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Invalid Playlist.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("errorInvalidPlaylist", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Invalid Playlist: Unexpected node: {0} in {1}.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("errorInvalidPlaylistNode", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}. Requires output to be hosted on a web server running IIS 7.0 with the Smooth Streaming handler installed and a Silverlight template that supports Smooth Streaming..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("errorNonSmoothStreamingServer", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Offlining interrupted by network loss.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("errorOfflineInterrupted", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Expected value in range {0} to {1} found {2}.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("errorValueOutOfRange", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} {1}.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerChapterItem", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Show chapters toggle.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerChapters", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Closed captions toggle.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerClosedCaptions", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Step backwards one frame.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerFrameStepBackwards", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Step forwards one frame.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerFrameStepForwards", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Full screen toggle.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerFullScreen", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to one hour.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerHour", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} hours.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerHours", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to one minute.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerMinute", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} minutes.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerMinutes", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Mute Toggle.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerMute", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Skip to next marker.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerNextMarker", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Make player available offline.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerOffline", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Click the cancel button to stop offline installation.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerOfflineProgressCancel", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Click the finish button to compete offline installation.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerOfflineProgressFinish", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Show playlist toggle.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerPlaylist", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to playlist item {0}. {1}..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerPlaylistItem", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Play pause toggle.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerPlayPause", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Show graphs.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerPlugIn", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Show player in seperate window.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerPopout", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Skip to previous marker.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerPreviousMarker", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to one second.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerSecond", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} seconds.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerSeconds", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Seek to time.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerSeekSlider", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Stop.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerStop", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Decrease volume.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerVolumeDown", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Set volume.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerVolumeSlider", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Increase volume.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("readerVolumeUp", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 23.98 IVTC..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12M_2398_BadFormat", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 24fps Film Sync..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12M_24_BadFormat", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 25fps PAL..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12M_25_BadFormat", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 29.97 DropFrame..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12M_2997_Drop_BadFormat", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Timecode frame value is not in the expected range for SMTPE 29.97 NonDrop..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12M_2997_NonDrop_BadFormat", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 30fps..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12M_30_BadFormat", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The timecode provided is not in the correct format..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12MBadFormat", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The timecode provided is out of the expected range..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12MOutOfRange", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The resulting timecode is out of the expected range of MaxValue..
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("Smpte12MOverflowException", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Click Finish to complete offline installation.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("textOfflineFinishPrompt", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Downloading content for offline playback.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("textOfflineProgressPrompt", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} of {1}.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("textOfflineProgressXOFYFormat", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Toggle chapters list (C).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipChapters", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Show/Hide closed captions (L).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipClosedCaptions", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Step backwards one frame (I).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipFrameStepBackwards", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Step forwards one frame (O).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipFrameStepForwards", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Toggle fullscreen playback (F).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipFullScreen", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Mute (M).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipMute", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Next Marker (N).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipNextMarker", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Make player available offline (D).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipOffline", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Click the cancel button to compete offline installation.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipOfflineProgressCancel", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Click Finish to complete offline installation.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipOfflineProgressFinish", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Toggle playlist (V).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipPlaylist", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Play/Pause (P).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipPlayPause", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Show Graphs (G).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipPlugIn", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Show player in seperate window (X).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipPopout", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Previous Marker (B).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipPreviousMarker", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Seek to time.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipSeekSlider", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Stop (S).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipStop", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Decrease Volume (J).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipVolumeDown", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Volume Slider.
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipVolumeSlider", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Increase Volume (K).
        ''' </summary>
        Public ReadOnly Property string() As
            Get

                return ResourceManager.GetString("tipVolumeUp", resourceCulture)
            End Get
        End Property
    End Class   '   Resources
' End Namespace   '   ExpressionMediaPlayer
' ..\Project_10\AdvancedMedia\1-AdvanceMedia\AdvMediaPlayer.Web\EncoderMedia\MediaPlayer\Resources\Resources.Designer.cs
