
' ------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:2.0.50727.4927
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

' Namespace FunBadge.Web

Partial Public Class SilverlightControl

    ''' <summary>
    ''' Silverlight1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Silverlight1 As System.Web.UI.SilverlightControls.Silverlight
End Class   '   SilverlightControl
' End Namespace   '   FunBadge.Web
' ..\Project_07\ASPAJAX\2-ASPUserControl\FunBadge.Web\FunBadge.ascx.designer.cs
