' ------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:2.0.50727.4927
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

' Namespace FunBadge.Web

    Public Partial Class _Default

        ''' <summary>
        ''' Head1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected Head1 As System.Web.UI.HtmlControls.HtmlHead

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected form1 As System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ScriptManager1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected ScriptManager1 As System.Web.UI.ScriptManager

        ''' <summary>
        ''' SilverlightControl3 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl3 As FunBadge.Web.SilverlightControl

        ''' <summary>
        ''' SilverlightControl1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl1 As FunBadge.Web.SilverlightControl

        ''' <summary>
        ''' SilverlightControl2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl2 As FunBadge.Web.SilverlightControl

        ''' <summary>
        ''' SilverlightControl4 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl4 As FunBadge.Web.SilverlightControl

        ''' <summary>
        ''' SilverlightControl5 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl5 As FunBadge.Web.SilverlightControl

        ''' <summary>
        ''' SilverlightControl6 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl6 As FunBadge.Web.SilverlightControl

        ''' <summary>
        ''' SilverlightControl7 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl7 As FunBadge.Web.SilverlightControl

        ''' <summary>
        ''' SilverlightControl8 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl8 As FunBadge.Web.SilverlightControl

        ''' <summary>
        ''' SilverlightControl9 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected SilverlightControl9 As FunBadge.Web.SilverlightControl
    End Class   '   _Default
' End Namespace   '   FunBadge.Web
' ..\Project_07\ASPAJAX\2-ASPUserControl\FunBadge.Web\TestMultipleBadge.aspx.designer.cs
