'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:2.0.50727.4927
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
'------------------------------------------------------------------------------
' Namespace RESTClient.Web

    Public Partial Class Get_Flickr

        ''' <summary>
        ''' Head1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
    Protected Head1 As System.Web.UI.HtmlControls.HtmlHead
    End Class   '   Get_Flickr
' End Namespace
' ..\Project_08\WebServices\1-RESTWebService\RESTClient.Web\2-GetFlickr.aspx.designer.cs
