Imports System

' ------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:2.0.50727.42
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

' Namespace AdoDataService

Partial Public Class _Default

    ''' <summary>
    ''' form1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected form1 As Web.UI.HtmlControls.HtmlForm
End Class   '   _Default
' End Namespace   '   AdoDataService
' ..\Project_07\ASPAJAX\4-AdoDataService\AdoDataService\Default.aspx.designer.cs
