' ------------------------------------------------------------------------------
'  <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<assembly: EdmSchemaAttribute()>
#Region "EDM Relationship Metadata"

<Assembly: EdmRelationshipAttribute("SilverlightResourceModel", "FK_Resource_ResourceType", "ResourceType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(AdoDataService.ResourceType), "Resource", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(AdoDataService.Resource))> 

#End Region

' Namespace AdoDataService

#Region "Contexts"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class SilverlightResourceEntities
        Inherits ObjectContext
#Region "Constructors"

    ''' <summary>
    ''' Initializes a new SilverlightResourceEntities object using the connection string found in the 'SilverlightResourceEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=SilverlightResourceEntities", "SilverlightResourceEntities")
        OnContextCreated()
    End Sub '   New
    ''' <summary>
    ''' Initialize a new SilverlightResourceEntities object.
    ''' </summary>
    Public Sub New(connectionString As String)
        MyBase.New(connectionString, "SilverlightResourceEntities")
        OnContextCreated()
    End Sub '   New
    ''' <summary>
    ''' Initialize a new SilverlightResourceEntities object.
    ''' </summary>
    Public Sub New(connection As EntityConnection)
        MyBase.New(connection, "SilverlightResourceEntities")
        OnContextCreated()
    End Sub '   New
#End Region

#Region "Partial Methods"

    Partial Private Sub OnContextCreated()

    End Sub '   OnContextCreated


#End Region

#Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Resource() As ObjectSet(Of Resource)
        Get
            If (_Resource Is Nothing) Then
                _Resource = MyBase.CreateObjectSet(Of Resource)("Resource")
            End If

            Return _Resource
        End Get
    End Property

    Private _Resource As ObjectSet(Of Resource)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ResourceType As ObjectSet(Of ResourceType)
        Get
            If (_ResourceType Is Nothing) Then
                _ResourceType = MyBase.CreateObjectSet(Of ResourceType)("ResourceType")
            End If

            Return _ResourceType
        End Get
    End Property

    Private _ResourceType As ObjectSet(Of ResourceType)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property sysdiagrams() As ObjectSet(Of sysdiagrams)
        Get
            If (_sysdiagrams Is Nothing) Then
                _sysdiagrams = MyBase.CreateObjectSet(Of sysdiagrams)("sysdiagrams")
            End If

            Return _sysdiagrams
        End Get
    End Property

    Private _sysdiagrams As ObjectSet(Of sysdiagrams)

#End Region

#Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Resource EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
    ''' </summary>
    Public Sub AddToResource(resource As Resource)

        MyBase.AddObject("Resource", resource)
    End Sub '   AddToResource
    ''' <summary>
    ''' Deprecated Method for adding a new object to the ResourceType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
    ''' </summary>
    Public Sub AddToResourceType(resourceType As ResourceType)

        MyBase.AddObject("ResourceType", resourceType)
    End Sub '   AddToResourceType
    ''' <summary>
    ''' Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
    ''' </summary>
    Public Sub AddTosysdiagrams(sysdiagrams As sysdiagrams)

        MyBase.AddObject("sysdiagrams", sysdiagrams)
    End Sub '   AddTosysdiagrams
    #End Region
End Class   '   SilverlightResourceEntities
#End Region

#Region "Entities"
''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SilverlightResourceModel", Name:="Resource")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Resource
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Resource object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateResource(id As Int32) As Resource

        Dim oResource As Resource = New resource()
        oResource.Id = id
        Return oResource
    End Function
#End Region

#Region "Primitive Properties"
    '' <summary>
    '' No Metadata Documentation available.
    '' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property Id() As Integer
        Get
            Return _Id
        End Get
        Set(value As Integer)
            If (_Id <> value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Integer

    Partial Private Sub OnIdChanging(value As Integer)

    End Sub '   OnIdChanging

    Partial Private Sub OnIdChanged()

    End Sub '   OnIdChanged
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Title() As String
        Get
            Return _Title
        End Get
        Set(value As String)

            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property

    Private _Title As String

    Partial Private Sub OnTitleChanging(value As String)

    End Sub '   OnTitleChanging

    Partial Private Sub OnTitleChanged()

    End Sub '   OnTitleChanged
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Author() As String
        Get

            Return _Author
        End Get
        Set(value As String)

            OnAuthorChanging(value)
            ReportPropertyChanging("Author")
            _Author = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Author")
            OnAuthorChanged()
        End Set
    End Property

    Private _Author As String

    Partial Private Sub OnAuthorChanging(value As String)

    End Sub '   OnAuthorChanging

    Partial Private Sub OnAuthorChanged()

    End Sub '   OnAuthorChanged

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Image() As String
        Get

            Return _Image
        End Get

        Set(value As String)

            OnImageChanging(value)
            ReportPropertyChanging("Image")
            _Image = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Image")
            OnImageChanged()
        End Set
    End Property

    Private _Image As String

    Partial Private Sub OnImageChanging(value As String)

    End Sub '   OnImageChanging

    Partial Private Sub OnImageChanged()

    End Sub '   OnImageChanged
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property URL() As String
        Get

            Return _URL
        End Get
        Set(value As String)

            OnURLChanging(value)
            ReportPropertyChanging("URL")
            _URL = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("URL")
            OnURLChanged()
        End Set
    End Property

    Private _URL As String

    Partial Private Sub OnURLChanging(value As String)

    End Sub '   OnURLChanging

    Partial Private Sub OnURLChanged()

    End Sub '   OnURLChanged
#End Region

#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SilverlightResourceModel", "FK_Resource_ResourceType", "ResourceType")>
    Public Property ResourceType() As ResourceType
        Get

            Return (CType(Me, IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of ResourceType)("SilverlightResourceModel.FK_Resource_ResourceType",
                                                                                                                  "ResourceType").Value
        End Get
        Set(value As ResourceType)

            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ResourceType)("SilverlightResourceModel.FK_Resource_ResourceType", "ResourceType").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ResourceTypeReference() As EntityReference(Of ResourceType)
        Get

            Return (CType(Me, IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of ResourceType)("SilverlightResourceModel.FK_Resource_ResourceType",
                                                                                                                  "ResourceType")
        End Get
        Set(value As EntityReference(Of ResourceType))

            If ((value IsNot Nothing)) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ResourceType)("SilverlightResourceModel.FK_Resource_ResourceType",
                                                                                                                    "ResourceType", value)
            End If
        End Set
    End Property

#End Region
End Class   '   Resource
''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SilverlightResourceModel", Name:="ResourceType")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class ResourceType
    Inherits EntityObject

#Region "Factory Method"

    ''' <summary>
    ''' Create a new ResourceType object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateResourceType(id As Int32) As ResourceType

        Dim oResourceType As ResourceType = New ResourceType()
        oResourceType.Id = id
        Return oResourceType

    End Function
#End Region

#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property Id() As Integer
        Get

            Return _Id
        End Get
        Set(value As Integer)

            If (_Id <> value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Integer

    Partial Private Sub OnIdChanging(value As Integer)

    End Sub '   OnIdChanging

    Partial Private Sub OnIdChanged()

    End Sub '   OnIdChanged
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Name() As String
        Get

            Return _Name
        End Get
        Set(value As String)

            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As String

    Partial Private Sub OnNameChanging(value As String)

    End Sub '   OnNameChanging

    Partial Private Sub OnNameChanged()

    End Sub '   OnNameChanged
#End Region

#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SilverlightResourceModel", "FK_Resource_ResourceType", "Resource")>
    Public Property Resource() As EntityCollection(Of Resource)
        Get

            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Resource)("SilverlightResourceModel.FK_Resource_ResourceType",
                                                                                                             "Resource")
        End Get

        Set(value As EntityCollection(Of Resource))

            If ((value IsNot Nothing)) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Resource)("SilverlightResourceModel.FK_Resource_ResourceType",
                                                                                                                 "Resource", value)
            End If
        End Set
    End Property
#End Region
End Class   '   ResourceType

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SilverlightResourceModel", name:="sysdiagrams")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class sysdiagrams
    Inherits EntityObject

#Region "Factory Method"

    ''' <summary>
    ''' Create a new sysdiagrams object.
    ''' </summary>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="principal_id">Initial value of the principal_id property.</param>
    ''' <param name="diagram_id">Initial value of the diagram_id property.</param>
    Public Shared Function Createsysdiagrams(name As String, principal_id As Int32, diagram_id As Int32) As sysdiagrams

        Dim oSysdiagrams As sysdiagrams = New sysdiagrams()
        oSysdiagrams.name = name
        oSysdiagrams.principal_id = principal_id
        oSysdiagrams.diagram_id = diagram_id
        Return oSysdiagrams
    End Function
#End Region

#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property name() As String
        Get

            Return _name
        End Get

        Set(value As String)

            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As String

    Partial Private Sub OnnameChanging(value As String)

    End Sub '   OnnameChanging

    Partial Private Sub OnnameChanged()

    End Sub '   OnnameChanged
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property principal_id() As Integer
        Get

            Return _principal_id
        End Get

        Set(value As Integer)

            Onprincipal_idChanging(value)
            ReportPropertyChanging("principal_id")
            _principal_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("principal_id")
            Onprincipal_idChanged()
        End Set
    End Property

    Private _principal_id As Integer

    Partial Private Sub Onprincipal_idChanging(value As Integer)

    End Sub '   Onprincipal_idChanging

    Partial Private Sub Onprincipal_idChanged()

    End Sub '   Onprincipal_idChanged

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property diagram_id() As Integer
        Get

            Return _diagram_id
        End Get

        Set(value As Integer)

            If (_diagram_id <> value) Then
                Ondiagram_idChanging(value)
                ReportPropertyChanging("diagram_id")
                _diagram_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("diagram_id")
                Ondiagram_idChanged()
            End If
        End Set
    End Property

    Private _diagram_id As Integer

    Partial Private Sub Ondiagram_idChanging(value As Integer)

    End Sub '   Ondiagram_idChanging

    Partial Private Sub Ondiagram_idChanged()

    End Sub '   Ondiagram_idChanged

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property version() As Nullable(Of Int32)
        Get

            Return _version
        End Get

        Set(value As Nullable(Of Int32))

            OnversionChanging(value)
            ReportPropertyChanging("version")
            _version = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("version")
            OnversionChanged()
        End Set
    End Property

    Private _version As Nullable(Of Int32)

    Partial Private Sub OnversionChanging(value As Nullable(Of Int32))

    End Sub '   OnversionChanging

    Partial Private Sub OnversionChanged()

    End Sub '   OnversionChanged

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property definition() As Byte()
        Get
            Return StructuralObject.GetValidValue(_definition)
        End Get
        Set(value As Byte())
            OndefinitionChanging(value)
            ReportPropertyChanging("definition")
            _definition = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("definition")
            OndefinitionChanged()
        End Set
    End Property

    Private _definition As Byte()

    Partial Private Sub OndefinitionChanging(value As Byte())

    End Sub '   OndefinitionChanging

    Partial Private Sub OndefinitionChanged()

    End Sub '   OndefinitionChanged
#End Region
End Class   '   sysdiagrams
#End Region
' End Namespace   '   AdoDataService
' ..\Project_07\ASPAJAX\4-AdoDataService\AdoDataService\SilverlightResource.Designer.cs
