'---------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by a tool.
'      Runtime Version:4.0.30319.1
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
'---------------------------------------------------------------------------

'
'  This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
' Namespace WCFClient.SilverlightResourceWCFService

Imports System.Runtime.Serialization

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")>
<System.Runtime.Serialization.DataContractAttribute(Name:="SilverlightResource.ResourceInfo", Namespace:="http://schemas.datacontract.org/2004/07/WCFClient.Web")>
Partial Public Structure SilverlightResourceResourceInfo
    Implements System.ComponentModel.INotifyPropertyChanged

    Private AuthorField As String
    Private ImageField As String
    Private TitleField As String
    Private TypeField As String
    Private URLField As String

    <System.Runtime.Serialization.DataMemberAttribute()>
    Public Property Author() As String
        Get
            Return Me.AuthorField
        End Get

        Set(value As String)

            If ((Object.ReferenceEquals(Me.AuthorField, value) <> True)) Then
                Me.AuthorField = value
                Me.RaisePropertyChanged("Author")
            End If
        End Set
    End Property

    <System.Runtime.Serialization.DataMemberAttribute()>
    Public Property Image() As String
        Get
            Return Me.ImageField
        End Get

        Set(value As String)
            If ((Object.ReferenceEquals(Me.ImageField, value) <> True)) Then
                Me.ImageField = value
                Me.RaisePropertyChanged("Image")
            End If
        End Set
    End Property

    <System.Runtime.Serialization.DataMemberAttribute()>
    Public Property Title() As String
        Get
            Return Me.TitleField
        End Get

        Set(value As String)
            If ((Object.ReferenceEquals(Me.TitleField, value) <> True)) Then
                Me.TitleField = value
                Me.RaisePropertyChanged("Title")
            End If
        End Set
    End Property

    <System.Runtime.Serialization.DataMemberAttribute()>
    Public Property Type() As String
        Get
            Return Me.TypeField
        End Get

        Set(value As String)
            If ((Object.ReferenceEquals(Me.TypeField, value) <> True)) Then
                Me.TypeField = value
                Me.RaisePropertyChanged("Type")
            End If
        End Set
    End Property


    <System.Runtime.Serialization.DataMemberAttribute()>
    Public Property URL() As String
        Get
            Return Me.URLField
        End Get

        Set(value As String)
            If ((Object.ReferenceEquals(Me.URLField, value) <> True)) Then
                Me.URLField = value
                Me.RaisePropertyChanged("URL")
            End If
        End Set
    End Property

    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

    Sub RaisePropertyChanged(propertyName As String)

        'Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChanged

        RaiseEvent PropertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
    End Sub '   RaisePropertyChanged
End Structure

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
<System.ServiceModel.ServiceContractAttribute(Namespace:="", ConfigurationName:="SilverlightResourceWCFService.SilverlightResource")>
Public Interface SilverlightResource

    <System.ServiceModel.OperationContractAttribute(AsyncPattern:=True, Action:="urn:SilverlightResource/GetResource", ReplyAction:="urn:SilverlightResource/GetResourceResponse")>
    Function BeginGetResource(id As Integer, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult
    Function EndGetResource(result As System.IAsyncResult) As SilverlightResourceResourceInfo
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
Public Interface SilverlightResourceChannel
    Inherits SilverlightResource
    Inherits System.ServiceModel.IClientChannel

End Interface

<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
Partial Public Class GetResourceCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs

    Private results As Object()

    Public Sub New(results As Object(), exception As System.Exception, cancelled As Boolean, userState As Object)
        MyBase.new(exception, cancelled, userState)

        Me.results = results
    End Sub '   New


    Public ReadOnly Property Result() As SilverlightResourceResourceInfo
        Get

            MyBase.RaiseExceptionIfNecessary()
            Return CType(Me.results(0), SilverlightResourceResourceInfo)
        End Get
    End Property
End Class   '   GetResourceCompletedEventArgs


<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
Partial Public Class SilverlightResourceClient
    Inherits System.ServiceModel.ClientBase(Of SilverlightResource)
    Implements SilverlightResource

    Private onBeginGetResourceDelegate As BeginOperationDelegate
    Private onEndGetResourceDelegate As EndOperationDelegate
    Private onGetResourceCompletedDelegate As System.Threading.SendOrPostCallback
    Private onBeginOpenDelegate As BeginOperationDelegate
    Private onEndOpenDelegate As EndOperationDelegate
    Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
    Private onBeginCloseDelegate As BeginOperationDelegate
    Private onEndCloseDelegate As EndOperationDelegate
    Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback

    Public Sub New()

    End Sub '   New


    Public Sub New(endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub '   New


    Public Sub New(endpointConfigurationName As String, remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub '   New


    Public Sub New(endpointConfigurationName As String, remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub '   New


    Public Sub New(binding As System.ServiceModel.Channels.Binding, remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub '   New


    Public Property CookieContainer() As System.Net.CookieContainer
        Get
            Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)()

            If (httpCookieContainerManager IsNot Nothing) Then
                Return httpCookieContainerManager.CookieContainer
            Else
                Return Nothing
            End If
        End Get
        Set(value As System.Net.CookieContainer)
            Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)()

            If ((httpCookieContainerManager IsNot Nothing)) Then
                httpCookieContainerManager.CookieContainer = value
            Else
                Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpCookieContainerBindingElement.")
            End If
        End Set
    End Property

    Public Event GetResourceCompleted As System.EventHandler(Of GetResourceCompletedEventArgs)

    Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)

    Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
    Function BeginGetResource(id As Integer, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult Implements SilverlightResource.BeginGetResource

        Return MyBase.Channel.BeginGetResource(id, callback, asyncState)
    End Function

    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
    Function EndGetResource(result As System.IAsyncResult) As SilverlightResourceResourceInfo Implements SilverlightResource.EndGetResource

        Return MyBase.Channel.EndGetResource(result)
    End Function

    Private Function OnBeginGetResource(inValues As Object(), callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult

        Dim id As Integer = CType(inValues(0), Integer)

        Return (CType(Me, SilverlightResource)).BeginGetResource(id, callback, asyncState)
    End Function  '   OnBeginGetResource


    Private Function OnEndGetResource(result As System.IAsyncResult) As Object()

        Dim retVal As SilverlightResourceResourceInfo = (CType(Me, SilverlightResource)).EndGetResource(result)

        Return New Object() {retVal}
    End Function

    Private Sub OnGetResourceCompleted(state As Object)

        Dim e As InvokeAsyncCompletedEventArgs = CType(state, InvokeAsyncCompletedEventArgs)
        RaiseEvent GetResourceCompleted(Me, New GetResourceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
    End Sub '   OnGetResourceCompleted

    Public Sub GetResourceAsync(id As Integer)

        Me.GetResourceAsync(id, Nothing)
    End Sub '   GetResourceAsync


    Public Sub GetResourceAsync(id As Integer, userState As Object)

        If ((Me.onBeginGetResourceDelegate = Nothing)) Then
            Me.onBeginGetResourceDelegate = New BeginOperationDelegate(AddressOf OnBeginGetResource)
        End If

        If ((Me.onEndGetResourceDelegate = Nothing)) Then
            Me.onEndGetResourceDelegate = New EndOperationDelegate(AddressOf OnEndGetResource)
        End If

        If ((Me.onGetResourceCompletedDelegate = Nothing)) Then
            Me.onGetResourceCompletedDelegate = New System.Threading.SendOrPostCallback(AddressOf OnGetResourceCompleted)
        End If

        MyBase.InvokeAsync(Me.onBeginGetResourceDelegate, New Object() {id}, Me.onEndGetResourceDelegate, Me.onGetResourceCompletedDelegate, userState)
    End Sub '   GetResourceAsync

    Private Function OnBeginOpen(inValues As Object(), callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult

        Return (CType(Me, System.ServiceModel.ICommunicationObject)).BeginOpen(callback, asyncState)
    End Function  '   OnBeginOpen


    Private Function OnEndOpen(result As System.IAsyncResult) As Object()

        CType(Me, System.ServiceModel.ICommunicationObject).EndOpen(result)
        Return Nothing
    End Function

    Private Sub OnOpenCompleted(state As Object)

        Dim e As InvokeAsyncCompletedEventArgs = CType(state, InvokeAsyncCompletedEventArgs)

        RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
    End Sub '   OnOpenCompleted

    Public Sub OpenAsync()

        Me.OpenAsync(Nothing)
    End Sub '   OpenAsync

    Public Sub OpenAsync(userState As Object)

        If ((Me.onBeginOpenDelegate = Nothing)) Then
            Me.onBeginOpenDelegate = New BeginOperationDelegate(AddressOf OnBeginOpen)
        End If

        If ((Me.onEndOpenDelegate = Nothing)) Then
            Me.onEndOpenDelegate = New EndOperationDelegate(AddressOf OnEndOpen)
        End If

        If ((Me.onOpenCompletedDelegate = Nothing)) Then
            Me.onOpenCompletedDelegate = New System.Threading.SendOrPostCallback(AddressOf OnOpenCompleted)
        End If

        MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
    End Sub '   OpenAsync

    Private Function OnBeginClose(inValues As Object(), callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult

        Return CType(Me, System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
    End Function  '   OnBeginClose

    Private Function OnEndClose(result As System.IAsyncResult) As Object()

        CType(Me, System.ServiceModel.ICommunicationObject).EndClose(result)
        Return Nothing
    End Function

    Private Sub OnCloseCompleted(state As Object)

        Dim e As InvokeAsyncCompletedEventArgs = CType(state, InvokeAsyncCompletedEventArgs)
        RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
    End Sub '   OnCloseCompleted

    Public Sub CloseAsync()

        Me.CloseAsync(Nothing)
    End Sub '   CloseAsync

    Public Sub CloseAsync(userState As Object)

        If ((Me.onBeginCloseDelegate = Nothing)) Then
            Me.onBeginCloseDelegate = New BeginOperationDelegate(AddressOf OnBeginClose)
        End If

        If ((Me.onEndCloseDelegate = Nothing)) Then
            Me.onEndCloseDelegate = New EndOperationDelegate(AddressOf OnEndClose)
        End If


        If ((Me.onCloseCompletedDelegate = Nothing)) Then
            Me.onCloseCompletedDelegate = New System.Threading.SendOrPostCallback(AddressOf OnCloseCompleted)
        End If

        MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
    End Sub '   CloseAsync

    Protected Overrides Function CreateChannel() As SilverlightResource

        Return New SilverlightResourceClientChannel(Me)
    End Function

    Private Class SilverlightResourceClientChannel
        Inherits ChannelBase(Of SilverlightResource)
        Implements SilverlightResource

        Public Sub New(client As System.ServiceModel.ClientBase(Of SilverlightResource))
            MyBase.New(client)
        End Sub '   New


        Public Function BeginGetResource(id As Integer, callback As System.AsyncCallback, asyncState As Object) As System.IAsyncResult Implements SilverlightResource.BeginGetResource

            Dim _args As Object()
            ReDim _args(0 To 0)
            _args(0) = id

            Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetResource", _args, callback, asyncState)

            Return _result
        End Function  '   BeginGetResource


        Public Function EndGetResource(result As System.IAsyncResult) As SilverlightResourceResourceInfo Implements SilverlightResource.EndGetResource

            Dim _args As Object()
            ReDim _args(0 To -1)
            Dim _result As SilverlightResourceResourceInfo = CType(MyBase.EndInvoke("GetResource", _args, result), SilverlightResourceResourceInfo)

            Return _result
        End Function
    End Class   '   SilverlightResourceClientChannel
End Class   '   SilverlightResourceClient
' End Namespace
' ..\Project_08\WebServices\3-WCFService\WCFClient\Service References\SilverlightResourceWCFService\Reference.cs
