'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Namespace SilverlightResourceWCFService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SilverlightResource.ResourceInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFClient.Web")>  _
    Partial Public Structure SilverlightResourceResourceInfo
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private AuthorField As String
        
        Private ImageField As String
        
        Private TitleField As String
        
        Private TypeField As String
        
        Private URLField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Author() As String
            Get
                Return Me.AuthorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuthorField, value) <> true) Then
                    Me.AuthorField = value
                    Me.RaisePropertyChanged("Author")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Image() As String
            Get
                Return Me.ImageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageField, value) <> true) Then
                    Me.ImageField = value
                    Me.RaisePropertyChanged("Image")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As String
            Get
                Return Me.TypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeField, value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property URL() As String
            Get
                Return Me.URLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.URLField, value) <> true) Then
                    Me.URLField = value
                    Me.RaisePropertyChanged("URL")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Structure
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="", ConfigurationName:="SilverlightResourceWCFService.SilverlightResource")>  _
    Public Interface SilverlightResource
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="urn:SilverlightResource/GetResource", ReplyAction:="urn:SilverlightResource/GetResourceResponse")>  _
        Function BeginGetResource(ByVal id As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetResource(ByVal result As System.IAsyncResult) As SilverlightResourceWCFService.SilverlightResourceResourceInfo
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SilverlightResourceChannel
        Inherits SilverlightResourceWCFService.SilverlightResource, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetResourceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As SilverlightResourceWCFService.SilverlightResourceResourceInfo
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SilverlightResourceWCFService.SilverlightResourceResourceInfo)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SilverlightResourceClient
        Inherits System.ServiceModel.ClientBase(Of SilverlightResourceWCFService.SilverlightResource)
        Implements SilverlightResourceWCFService.SilverlightResource
        
        Private onBeginGetResourceDelegate As BeginOperationDelegate
        
        Private onEndGetResourceDelegate As EndOperationDelegate
        
        Private onGetResourceCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event GetResourceCompleted As System.EventHandler(Of GetResourceCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SilverlightResourceWCFService_SilverlightResource_BeginGetResource(ByVal id As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SilverlightResourceWCFService.SilverlightResource.BeginGetResource
            Return MyBase.Channel.BeginGetResource(id, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SilverlightResourceWCFService_SilverlightResource_EndGetResource(ByVal result As System.IAsyncResult) As SilverlightResourceWCFService.SilverlightResourceResourceInfo Implements SilverlightResourceWCFService.SilverlightResource.EndGetResource
            Return MyBase.Channel.EndGetResource(result)
        End Function
        
        Private Function OnBeginGetResource(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim id As Integer = CType(inValues(0),Integer)
            Return CType(Me,SilverlightResourceWCFService.SilverlightResource).BeginGetResource(id, callback, asyncState)
        End Function
        
        Private Function OnEndGetResource(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As SilverlightResourceWCFService.SilverlightResourceResourceInfo = CType(Me,SilverlightResourceWCFService.SilverlightResource).EndGetResource(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetResourceCompleted(ByVal state As Object)
            If (Not (Me.GetResourceCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetResourceCompleted(Me, New GetResourceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetResourceAsync(ByVal id As Integer)
            Me.GetResourceAsync(id, Nothing)
        End Sub
        
        Public Overloads Sub GetResourceAsync(ByVal id As Integer, ByVal userState As Object)
            If (Me.onBeginGetResourceDelegate Is Nothing) Then
                Me.onBeginGetResourceDelegate = AddressOf Me.OnBeginGetResource
            End If
            If (Me.onEndGetResourceDelegate Is Nothing) Then
                Me.onEndGetResourceDelegate = AddressOf Me.OnEndGetResource
            End If
            If (Me.onGetResourceCompletedDelegate Is Nothing) Then
                Me.onGetResourceCompletedDelegate = AddressOf Me.OnGetResourceCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetResourceDelegate, New Object() {id}, Me.onEndGetResourceDelegate, Me.onGetResourceCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As SilverlightResourceWCFService.SilverlightResource
            Return New SilverlightResourceClientChannel(Me)
        End Function
        
        Private Class SilverlightResourceClientChannel
            Inherits ChannelBase(Of SilverlightResourceWCFService.SilverlightResource)
            Implements SilverlightResourceWCFService.SilverlightResource
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of SilverlightResourceWCFService.SilverlightResource))
                MyBase.New(client)
            End Sub
            
            Public Function BeginGetResource(ByVal id As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SilverlightResourceWCFService.SilverlightResource.BeginGetResource
                Dim _args((1) - 1) As Object
                _args(0) = id
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetResource", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetResource(ByVal result As System.IAsyncResult) As SilverlightResourceWCFService.SilverlightResourceResourceInfo Implements SilverlightResourceWCFService.SilverlightResource.EndGetResource
                Dim _args((0) - 1) As Object
                Dim _result As SilverlightResourceWCFService.SilverlightResourceResourceInfo = CType(MyBase.EndInvoke("GetResource", _args, result),SilverlightResourceWCFService.SilverlightResourceResourceInfo)
                Return _result
            End Function
        End Class
    End Class
End Namespace
